# Generated by Django 6.0.8 on 2026-10-03 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'Devam ediyor'), ('completed', 'Tamamlandı'), ('expired', 'Süresi doldu')], default='in_progress', max_length=20)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('player_name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_type', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], default='web', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='quiz.category')),
            ],
            options={
                'db_table': 'quiz_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.choice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_sessions.quizsession')),
            ],
            options={
                'db_table': 'session_answers',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(condition=models.Q(('player_name__isnull', False)), fields=['category', '-score', 'finished_at'], name='leaderboard_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionanswer',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='uniq_session_position'),
        ),
    ]
